GET http://localhost:3003/api/blogs

###

GET http://localhost:3001/api/persons/1

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Blog",
  "author": "John Doe",
  "url": "http://example.com",
  "likes": 0
}

###

PUT http://localhost:3001/api/persons/1
Content-Type: application/json

{
  "name": "John Doe",
  "number": "123-4567890"
}

###

DELETE http://localhost:3001/api/persons/1



